// Role: the the-registry kernel reference tables, generated from its config. KINDS are the adopted common kinds plus the local kinds; SOURCES is the config's source table; ADOPTED names the shared common kinds this kernel pins and ADOPTED_HASHES freezes the pinned type-hashes at adoption.
// Contract: exports KINDS, SOURCES, ADOPTED, ADOPTED_HASHES, TIME_LOCK. Pure data; imports nothing.
// Invariant: the adopted hashes are frozen from corpora/_shared/common-types.js at generation; the real check verifies they still match the shared subtree, so a stale pin is caught.
// GENERATED by scaffolder/new-kernel.mjs from a kernel config; do not hand-edit.
"use strict";

const KINDS = [
  {
    "kind": "extension",
    "ceiling": "checked"
  },
  {
    "kind": "skin",
    "ceiling": "checked"
  },
  {
    "kind": "component",
    "ceiling": "checked"
  },
  {
    "kind": "client",
    "ceiling": "checked"
  },
  {
    "kind": "community",
    "ceiling": "checked"
  },
  {
    "kind": "contract-bundle",
    "ceiling": "constitutive"
  }
];

const SOURCES = [
  {
    "source_id": "S-registry-oracles",
    "source_class": "primary-measurement",
    "description": "this deployment's own conformance oracles (build/check-extension-seam.mjs's ranking-separation fuzz, build/check-skins.mjs's per-skin assertions, and other sandbox-executable checks), re-run directly against the artifact each artifact-card claim names"
  },
  {
    "source_id": "S-registry-ci-only",
    "source_class": "institutional-report",
    "description": "a conformance oracle that only executes in this repository's own CI (build/check-conformance-read.mjs and build/check-conformance-write.mjs, the independent-minimal-client pair), cited as recomputable in the repository, never as app-verified"
  }
];

// the shared common kinds this kernel adopts (names), and the type-hashes pinned at adoption.
const ADOPTED = [];
const ADOPTED_HASHES = {};

// time-lock and standing (F5): the one clean free parameter, no grounding consequence.
const TIME_LOCK = {
  "setting": "light"
};

module.exports = { KINDS, SOURCES, ADOPTED, ADOPTED_HASHES, TIME_LOCK };
