// Role: the epistack-competition kernel reference tables, generated from its config. KINDS are the adopted common kinds plus the local kinds; SOURCES is the config's source table; ADOPTED names the shared common kinds this kernel pins and ADOPTED_HASHES freezes the pinned type-hashes at adoption.
// Contract: exports KINDS, SOURCES, ADOPTED, ADOPTED_HASHES, TIME_LOCK. Pure data; imports nothing.
// Invariant: the adopted hashes are frozen from corpora/_shared/common-types.js at generation; the real check verifies they still match the shared subtree, so a stale pin is caught.
// GENERATED by scaffolder/new-kernel.mjs from a kernel config; do not hand-edit.
"use strict";

const KINDS = [
  {
    "kind": "measurement",
    "ceiling": "checked"
  },
  {
    "kind": "forum",
    "ceiling": "corroborated"
  }
];

const SOURCES = [
  {
    "source_id": "S-epistack-protocol-spec",
    "source_class": "institutional-report",
    "description": "the pinned reference implementation's own protocol-spec.md, composition-spec.md, ecosystem-guide.md, and parameters-register.md, the asserting source for this kernel's mechanical claims about what the protocol guarantees"
  },
  {
    "source_id": "S-epistack-submission-argument",
    "source_class": "preprint",
    "description": "the pinned reference implementation's own epistemic_uplift.md, compost-ledger.md, and trust-and-view.md, unreviewed argumentative essays awaiting the judges' own semantic acceptance, the asserting source for this kernel's evaluative claims"
  }
];

// the shared common kinds this kernel adopts (names), and the type-hashes pinned at adoption.
const ADOPTED = [
  "measurement",
  "forum"
];
const ADOPTED_HASHES = {
  "measurement": "2ed60a0154fef12d5d630f4a3f52d06686479c75aa57a44fd3b1488d581d3621",
  "forum": "04c5a97678a1228065e6c36068b0b3dcc12ca52ad1285e6727f49754030007a1"
};

// time-lock and standing (F5): the one clean free parameter, no grounding consequence.
const TIME_LOCK = {
  "setting": "light"
};

module.exports = { KINDS, SOURCES, ADOPTED, ADOPTED_HASHES, TIME_LOCK };
