// Role: the knowledge-game kernel reference tables, generated from its config. KINDS are the adopted common kinds plus the local kinds; SOURCES is the config's source table; ADOPTED names the shared common kinds this kernel pins and ADOPTED_HASHES freezes the pinned type-hashes at adoption.
// Contract: exports KINDS, SOURCES, ADOPTED, ADOPTED_HASHES, TIME_LOCK. Pure data; imports nothing.
// Invariant: the adopted hashes are frozen from corpora/_shared/common-types.js at generation; the real check verifies they still match the shared subtree, so a stale pin is caught.
// GENERATED by scaffolder/new-kernel.mjs from a kernel config; do not hand-edit.
// DEPARTURE (the entrance listing): the "identity" kind (ceiling constitutive, for the title, tagline,
//   and link listing claims) was added by hand rather than by re-running the scaffolder, since doing so
//   against this kernel's config would overwrite knowledge-game-data.js's own 20 hand-grounded claims
//   with an empty skeleton (new-kernel.mjs always emits a fresh, empty <id>-data.js). The config file
//   (kernel-config.json) names this kind in local_kinds so its own intent stays legible even though the
//   two files were not regenerated together this time; the-registry's own tables.js carries the
//   identical pattern (a constitutive-ceiling kind, contract-bundle, alongside checked-ceiling ones).
// DEPARTURE (the front-page decomposition claims): "declaration" and "forum", both shared common kinds
//   (vendor/corpora/_shared/common-types.js), adopted by hand for the identical reason: definitional
//   statements (declaration, ceiling constitutive) and interpretive weighings (forum, ceiling
//   corroborated) the front page's own six answers decompose into, honestly typed rather than forced
//   into "identity" or "measurement".
"use strict";

const KINDS = [
  {
    "kind": "measurement",
    "ceiling": "checked"
  },
  {
    "kind": "identity",
    "ceiling": "constitutive"
  },
  {
    "kind": "declaration",
    "ceiling": "constitutive"
  },
  {
    "kind": "forum",
    "ceiling": "corroborated"
  }
];

const SOURCES = [
  {
    "source_id": "S-kg-spec-v2",
    "source_class": "institutional-report",
    "description": "knowledge-game-spec-v2.md (this deployment's own specification, Sections 2, 5, and 9) and kernel/governance/stage-0.md, the asserting source for every governance claim this kernel carries about the app's own behavior"
  },
  {
    "source_id": "contributor:cite:knowledgegamespecv2-md-section-6-the-extension-s",
    "source_class": "testimony",
    "description": "knowledgegamespecv2.md Section 6, the extension seam guarantee. This source was minted by api/contribute.js's own citationSource() when claim-20 was drafted through the app's real contribution path (Phase KG-4); it is testimony-class, the honest floor the app's citation mechanism ever produces, distinct from S-kg-spec-v2's institutional-report class the hand-authored claims cite directly."
  },
  {
    "source_id": "S-kg-self-stipulated",
    "source_class": "institutional-report",
    "description": "this deployment's own stipulated identity (name, tagline, and canonical locations): adopted by the operator, not measured, the same honest floor a constitutive-ceiling kind's own claim ever carries"
  },
  {
    "source_id": "S-fp-self-declared",
    "source_class": "institutional-report",
    "description": "this deployment's own front page (index.html): the submission's argument, restated as the definitional and app-behavior claims the page itself stipulates or already grounds elsewhere in this kernel"
  },
  {
    "source_id": "S-fp-epistack-submission",
    "source_class": "institutional-report",
    "description": "the epistack submission repository's own docs and corpora, cited by the front page's own doors; these claims enter at the honest floor a citation alone ever earns, awaiting a local fork that would type them"
  }
];

// the shared common kinds this kernel adopts (names), and the type-hashes pinned at adoption.
const ADOPTED = [
  "measurement",
  "declaration",
  "forum"
];
const ADOPTED_HASHES = {
  "measurement": "2ed60a0154fef12d5d630f4a3f52d06686479c75aa57a44fd3b1488d581d3621",
  "declaration": "354cba45e263a9788064fbf35d71d8506dd93ddf8c35b092ba606e5c2cc3b1bd",
  "forum": "04c5a97678a1228065e6c36068b0b3dcc12ca52ad1285e6727f49754030007a1"
};

// time-lock and standing (F5): the one clean free parameter, no grounding consequence.
const TIME_LOCK = {
  "setting": "light"
};

module.exports = { KINDS, SOURCES, ADOPTED, ADOPTED_HASHES, TIME_LOCK };
