// Role: the knowledge-game kernel reference tables, generated from its config. KINDS are the adopted common kinds plus the local kinds; SOURCES is the config's source table; ADOPTED names the shared common kinds this kernel pins and ADOPTED_HASHES freezes the pinned type-hashes at adoption.
// Contract: exports KINDS, SOURCES, ADOPTED, ADOPTED_HASHES, TIME_LOCK. Pure data; imports nothing.
// Invariant: the adopted hashes are frozen from corpora/_shared/common-types.js at generation; the real check verifies they still match the shared subtree, so a stale pin is caught.
// GENERATED by scaffolder/new-kernel.mjs from a kernel config; do not hand-edit.
"use strict";

const KINDS = [
  {
    "kind": "measurement",
    "ceiling": "checked"
  }
];

const SOURCES = [
  {
    "source_id": "S-kg-spec-v2",
    "source_class": "institutional-report",
    "description": "knowledge-game-spec-v2.md (this deployment's own specification, Sections 2, 5, and 9) and kernel/governance/stage-0.md, the asserting source for every governance claim this kernel carries about the app's own behavior"
  },
  {
    "source_id": "contributor:cite:knowledgegamespecv2-md-section-6-the-extension-s",
    "source_class": "testimony",
    "description": "knowledgegamespecv2.md Section 6, the extension seam guarantee. This source was minted by api/contribute.js's own citationSource() when claim-20 was drafted through the app's real contribution path (Phase KG-4); it is testimony-class, the honest floor the app's citation mechanism ever produces, distinct from S-kg-spec-v2's institutional-report class the hand-authored claims cite directly."
  }
];

// the shared common kinds this kernel adopts (names), and the type-hashes pinned at adoption.
const ADOPTED = [
  "measurement"
];
const ADOPTED_HASHES = {
  "measurement": "2ed60a0154fef12d5d630f4a3f52d06686479c75aa57a44fd3b1488d581d3621"
};

// time-lock and standing (F5): the one clean free parameter, no grounding consequence.
const TIME_LOCK = {
  "setting": "light"
};

module.exports = { KINDS, SOURCES, ADOPTED, ADOPTED_HASHES, TIME_LOCK };
