// Role: the knowledge-game kernel reference tables, generated from its config. KINDS are the adopted common kinds plus the local kinds; SOURCES is the config's source table; ADOPTED names the shared common kinds this kernel pins and ADOPTED_HASHES freezes the pinned type-hashes at adoption.
// Contract: exports KINDS, SOURCES, ADOPTED, ADOPTED_HASHES, TIME_LOCK. Pure data; imports nothing.
// Invariant: the adopted hashes are frozen from corpora/_shared/common-types.js at generation; the real check verifies they still match the shared subtree, so a stale pin is caught.
// GENERATED by scaffolder/new-kernel.mjs from a kernel config; do not hand-edit.
// DEPARTURE (the entrance listing): the "identity" kind (ceiling constitutive, for the title, tagline,
//   and link listing claims) was added by hand rather than by re-running the scaffolder, since doing so
//   against this kernel's config would overwrite knowledge-game-data.js's own 20 hand-grounded claims
//   with an empty skeleton (new-kernel.mjs always emits a fresh, empty <id>-data.js). The config file
//   (kernel-config.json) names this kind in local_kinds so its own intent stays legible even though the
//   two files were not regenerated together this time; the-registry's own tables.js carries the
//   identical pattern (a constitutive-ceiling kind, contract-bundle, alongside checked-ceiling ones).
"use strict";

const KINDS = [
  {
    "kind": "measurement",
    "ceiling": "checked"
  },
  {
    "kind": "identity",
    "ceiling": "constitutive"
  }
];

const SOURCES = [
  {
    "source_id": "S-kg-spec-v2",
    "source_class": "institutional-report",
    "description": "knowledge-game-spec-v2.md (this deployment's own specification, Sections 2, 5, and 9) and kernel/governance/stage-0.md, the asserting source for every governance claim this kernel carries about the app's own behavior"
  },
  {
    "source_id": "contributor:cite:knowledgegamespecv2-md-section-6-the-extension-s",
    "source_class": "testimony",
    "description": "knowledgegamespecv2.md Section 6, the extension seam guarantee. This source was minted by api/contribute.js's own citationSource() when claim-20 was drafted through the app's real contribution path (Phase KG-4); it is testimony-class, the honest floor the app's citation mechanism ever produces, distinct from S-kg-spec-v2's institutional-report class the hand-authored claims cite directly."
  },
  {
    "source_id": "S-kg-self-stipulated",
    "source_class": "institutional-report",
    "description": "this deployment's own stipulated identity (name, tagline, and canonical locations): adopted by the operator, not measured, the same honest floor a constitutive-ceiling kind's own claim ever carries"
  }
];

// the shared common kinds this kernel adopts (names), and the type-hashes pinned at adoption.
const ADOPTED = [
  "measurement"
];
const ADOPTED_HASHES = {
  "measurement": "2ed60a0154fef12d5d630f4a3f52d06686479c75aa57a44fd3b1488d581d3621"
};

// time-lock and standing (F5): the one clean free parameter, no grounding consequence.
const TIME_LOCK = {
  "setting": "light"
};

module.exports = { KINDS, SOURCES, ADOPTED, ADOPTED_HASHES, TIME_LOCK };
